name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0' # Adjust to your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel deploy --prod --yes --token=$VERCEL_TOKEN

        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
